notifications:
  recipients:
    - koji.shimada@enishi-tech.com
    - adzuki34@gmail.com
language: ruby
rvm:
  - 1.9.3
install:
  - echo "deb http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee /etc/apt/sources.list.d/groonga.list
  - sudo apt-get update
  - sudo apt-get -y --allow-unauthenticated install groonga-keyring
  - sudo apt-get -y purge zeromq
  - sudo apt-get update
  - sudo apt-get -y install groonga libgroonga-dev
  - bundle install
