notifications:
  recipients:
    - koji.shimada@enishi-tech.com
    - adzuki34@gmail.com
    - kou@clear-code.com
language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development:production"
before_script:
  - cp config/database.yml.example config/database.yml
  - cp .env.sample .env
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate --trace
before_install:
  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
